import 'package:flutter/material.dart';

class AppUser {
  AppUser({
    @required this.id,
    @required this.name,
    @required this.avatar,
  });

  final String id;
  final String name;
  final AppUserAvatar avatar;
}

enum AppUserAvatar {
  agnaktor,
  akantor,
  arzuros,
  azureRathalos,
  balefulGigginox,
  barioth,
  barroth,
  blackDiablos,
  blueYianKutKu,
  bruteTigrex,
  bulldrome,
  crimsonQurupeco,
  deviljho,
  diablos,
  duramboros,
  gigginox,
  glacialAgnaktor,
  gobul,
  goldRathian,
  greatBaggi,
  greatJaggi,
  greatWroggi,
  greenNargacuga,
  jadeBarroth,
  jhenMohran,
  khezu,
  kirin,
  lagombi,
  nargacuga,
  nibelsnarf,
  oroshiKirin,
  pinkRathian,
  purpleLudroth,
  qurupeco,
  rajang,
  rathalos,
  rathian,
  redKhezu,
  royalLudroth,
  rustDuramboros,
  sandBarioth,
  seltasQueen,
  seltas,
  silverRathalos,
  steelUragaan,
  stygianZinogre,
  tigrex,
  ukanlos,
  uragaan,
  volvidon,
  yianKutKu,
  zinogre,
  unknown,
}

extension AppUserAvatarExtension on AppUserAvatar {
  static final _idList = {
    AppUserAvatar.agnaktor: 1,
    AppUserAvatar.akantor: 2,
    AppUserAvatar.arzuros: 3,
    AppUserAvatar.azureRathalos: 4,
    AppUserAvatar.balefulGigginox: 5,
    AppUserAvatar.barioth: 6,
    AppUserAvatar.barroth: 7,
    AppUserAvatar.blackDiablos: 8,
    AppUserAvatar.blueYianKutKu: 9,
    AppUserAvatar.bruteTigrex: 10,
    AppUserAvatar.bulldrome: 11,
    AppUserAvatar.crimsonQurupeco: 12,
    AppUserAvatar.deviljho: 13,
    AppUserAvatar.diablos: 14,
    AppUserAvatar.duramboros: 15,
    AppUserAvatar.gigginox: 16,
    AppUserAvatar.glacialAgnaktor: 17,
    AppUserAvatar.gobul: 18,
    AppUserAvatar.goldRathian: 19,
    AppUserAvatar.greatBaggi: 21,
    AppUserAvatar.greatJaggi: 21,
    AppUserAvatar.greatWroggi: 22,
    AppUserAvatar.greenNargacuga: 23,
    AppUserAvatar.jadeBarroth: 24,
    AppUserAvatar.jhenMohran: 25,
    AppUserAvatar.khezu: 26,
    AppUserAvatar.kirin: 27,
    AppUserAvatar.lagombi: 28,
    AppUserAvatar.nargacuga: 29,
    AppUserAvatar.nibelsnarf: 30,
    AppUserAvatar.oroshiKirin: 31,
    AppUserAvatar.pinkRathian: 32,
    AppUserAvatar.purpleLudroth: 33,
    AppUserAvatar.qurupeco: 34,
    AppUserAvatar.rajang: 35,
    AppUserAvatar.rathalos: 36,
    AppUserAvatar.rathian: 37,
    AppUserAvatar.redKhezu: 38,
    AppUserAvatar.royalLudroth: 39,
    AppUserAvatar.rustDuramboros: 40,
    AppUserAvatar.sandBarioth: 41,
    AppUserAvatar.seltasQueen: 42,
    AppUserAvatar.seltas: 43,
    AppUserAvatar.silverRathalos: 44,
    AppUserAvatar.steelUragaan: 45,
    AppUserAvatar.stygianZinogre: 46,
    AppUserAvatar.tigrex: 47,
    AppUserAvatar.ukanlos: 48,
    AppUserAvatar.uragaan: 49,
    AppUserAvatar.volvidon: 50,
    AppUserAvatar.yianKutKu: 51,
    AppUserAvatar.zinogre: 52,
    AppUserAvatar.unknown: 53,
  };
  int get id => _idList[this];

  static final _names = {
    AppUserAvatar.agnaktor: 'アグナコトル',
    AppUserAvatar.akantor: 'アカムトルム',
    AppUserAvatar.arzuros: 'アオアシラ',
    AppUserAvatar.azureRathalos: 'リオレウス亜種',
    AppUserAvatar.balefulGigginox: 'ギギネブラ亜種',
    AppUserAvatar.barioth: 'ベリオロス',
    AppUserAvatar.barroth: 'ボルボロス',
    AppUserAvatar.blackDiablos: 'ディアブロス亜種',
    AppUserAvatar.blueYianKutKu: 'イャンクック亜種',
    AppUserAvatar.bruteTigrex: 'ティガレックス亜種',
    AppUserAvatar.bulldrome: 'ドスファンゴ',
    AppUserAvatar.crimsonQurupeco: 'クルペッコ亜種',
    AppUserAvatar.deviljho: 'イビルジョー',
    AppUserAvatar.diablos: 'ディアブロス',
    AppUserAvatar.duramboros: 'ドボルベルク',
    AppUserAvatar.gigginox: 'ギギネブラ',
    AppUserAvatar.glacialAgnaktor: 'アグナコトル亜種',
    AppUserAvatar.gobul: 'チャナガブル',
    AppUserAvatar.goldRathian: 'リオレイア希少種',
    AppUserAvatar.greatBaggi: 'ドスバギィ',
    AppUserAvatar.greatJaggi: 'ドスジャギィ',
    AppUserAvatar.greatWroggi: 'ドスフロギィ',
    AppUserAvatar.greenNargacuga: 'ナルガクルガ亜種',
    AppUserAvatar.jadeBarroth: 'ボルボロス亜種',
    AppUserAvatar.jhenMohran: 'ジエン・モーラン',
    AppUserAvatar.khezu: 'フルフル',
    AppUserAvatar.kirin: 'キリン',
    AppUserAvatar.lagombi: 'ウルクスス',
    AppUserAvatar.nargacuga: 'ナルガクルガ',
    AppUserAvatar.nibelsnarf: 'ハプルボッカ',
    AppUserAvatar.oroshiKirin: 'キリン亜種',
    AppUserAvatar.pinkRathian: 'リオレイア亜種',
    AppUserAvatar.purpleLudroth: 'ロアルドロス亜種',
    AppUserAvatar.qurupeco: 'クルペッコ',
    AppUserAvatar.rajang: 'ラージャン',
    AppUserAvatar.rathalos: 'リオレウス',
    AppUserAvatar.rathian: 'リオレイア',
    AppUserAvatar.redKhezu: 'フルフル亜種',
    AppUserAvatar.royalLudroth: 'ロアルドロス',
    AppUserAvatar.rustDuramboros: 'ドボルベルク亜種',
    AppUserAvatar.sandBarioth: 'ベリオロス亜種',
    AppUserAvatar.seltasQueen: 'ゲネル・セルタス',
    AppUserAvatar.seltas: 'アルセルタス',
    AppUserAvatar.silverRathalos: 'リオレウス希少種',
    AppUserAvatar.steelUragaan: 'ウラガンキン亜種',
    AppUserAvatar.stygianZinogre: 'ジンオウガ亜種',
    AppUserAvatar.tigrex: 'ティガレックス',
    AppUserAvatar.ukanlos: 'ウカムルバス',
    AppUserAvatar.uragaan: 'ウラガンキン',
    AppUserAvatar.volvidon: 'ラングロトラ',
    AppUserAvatar.yianKutKu: 'イャンクック',
    AppUserAvatar.zinogre: 'ジンオウガ',
    AppUserAvatar.unknown: 'Unknown',
  };
  String get name => _names[this];

  static const _path = 'assets/icons/monsters';
  static final _filePaths = {
    AppUserAvatar.agnaktor: '$_path/agnaktor.png',
    AppUserAvatar.akantor: '$_path/akantor.png',
    AppUserAvatar.arzuros: '$_path/arzuros.png',
    AppUserAvatar.azureRathalos: '$_path/azure_rathalos.png',
    AppUserAvatar.balefulGigginox: '$_path/baleful_gigginox.png',
    AppUserAvatar.barioth: '$_path/barioth.png',
    AppUserAvatar.barroth: '$_path/barroth.png',
    AppUserAvatar.blackDiablos: '$_path/black_diablos.png',
    AppUserAvatar.blueYianKutKu: '$_path/blue_yian_kut-ku.png',
    AppUserAvatar.bruteTigrex: '$_path/brute_tigrex.png',
    AppUserAvatar.bulldrome: '$_path/bulldrome.png',
    AppUserAvatar.crimsonQurupeco: '$_path/crimson_qurupeco.png',
    AppUserAvatar.deviljho: '$_path/deviljho.png',
    AppUserAvatar.diablos: '$_path/diablos.png',
    AppUserAvatar.duramboros: '$_path/duramboros.png',
    AppUserAvatar.gigginox: '$_path/gigginox.png',
    AppUserAvatar.glacialAgnaktor: '$_path/glacial_agnaktor.png',
    AppUserAvatar.gobul: '$_path/gobul.png',
    AppUserAvatar.goldRathian: '$_path/gold_rathian.png',
    AppUserAvatar.greatBaggi: '$_path/great_baggi.png',
    AppUserAvatar.greatJaggi: '$_path/great_jaggi.png',
    AppUserAvatar.greatWroggi: '$_path/great_wroggi.png',
    AppUserAvatar.greenNargacuga: '$_path/green_nargacuga.png',
    AppUserAvatar.jadeBarroth: '$_path/jade_barroth.png',
    AppUserAvatar.jhenMohran: '$_path/jhen_mohran.png',
    AppUserAvatar.khezu: '$_path/khezu.png',
    AppUserAvatar.kirin: '$_path/kirin.png',
    AppUserAvatar.lagombi: '$_path/lagombi.png',
    AppUserAvatar.nargacuga: '$_path/nargacuga.png',
    AppUserAvatar.nibelsnarf: '$_path/nibelsnarf.png',
    AppUserAvatar.oroshiKirin: '$_path/oroshi_kirin.png',
    AppUserAvatar.pinkRathian: '$_path/pink_rathian.png',
    AppUserAvatar.purpleLudroth: '$_path/purple_ludroth.png',
    AppUserAvatar.qurupeco: '$_path/qurupeco.png',
    AppUserAvatar.rajang: '$_path/rajang.png',
    AppUserAvatar.rathalos: '$_path/rathalos.png',
    AppUserAvatar.rathian: '$_path/rathian.png',
    AppUserAvatar.redKhezu: '$_path/red_khezu.png',
    AppUserAvatar.royalLudroth: '$_path/royal_ludroth.png',
    AppUserAvatar.rustDuramboros: '$_path/rust_duramboros.png',
    AppUserAvatar.sandBarioth: '$_path/sand_barioth.png',
    AppUserAvatar.seltasQueen: '$_path/seltas_queen.png',
    AppUserAvatar.seltas: '$_path/seltas.png',
    AppUserAvatar.silverRathalos: '$_path/silver_rathalos.png',
    AppUserAvatar.steelUragaan: '$_path/steel_uragaan.png',
    AppUserAvatar.stygianZinogre: '$_path/stygian_zinogre.png',
    AppUserAvatar.tigrex: '$_path/tigrex.png',
    AppUserAvatar.ukanlos: '$_path/ukanlos.png',
    AppUserAvatar.uragaan: '$_path/uragaan.png',
    AppUserAvatar.volvidon: '$_path/volvidon.png',
    AppUserAvatar.yianKutKu: '$_path/yian_kut-ku.png',
    AppUserAvatar.zinogre: '$_path/zinogre.png',
    AppUserAvatar.unknown: '$_path/unknown.png',
  };
  String get filePath => _filePaths[this];
}

AppUserAvatar getAppUserAvatar({@required int id}) {
  for (final avatar in AppUserAvatar.values) {
    if (avatar.id == id) {
      return avatar;
    }
  }
  return AppUserAvatar.unknown;
}
